version: "3.8"
services:
  nsp_backend:
    container_name: server
    image: express_postgres
    build:
      context: .
    ports:
      - "80:3002"
    environment:
      - EXTERNAL_PORT=3002
      - PGUSER=postgres
      - PGPASSWORD=post@123
      - PGDATABASE=todo_database
      - PGHOST=nsp_db # NAME OF THE SERVICE
    depends_on:
      - nsp_db
  nsp_db:
    container_name: nsp_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post@123
      - POSTGRES_DB=todo_database
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}
